const COSMO_CACHE = 'cosmo-kid-v74-mobile-fullscreen';
const CORE = [
  './',
  './index.html?v=74',
  './game.html?v=74',

  './diagnostico.html?v=74',
  './manifest.webmanifest',
  './assets/cover/cosmokid_cover.png',
  './assets/cover/cosmokid_cover_premium_wide.jpg',
  './assets/cover/cosmokid_cover_premium_mobile.jpg',
  './assets/cover/cosmokid_cover_premium_banner.jpg',
  './assets/icons/icon-192.png',
  './assets/icons/icon-512.png',
  './assets/icons/icon-512.png',
  './assets/rocks/roca_01.png',
  './assets/rocks/roca_02.png',
  './assets/rocks/roca_03.png',
  './assets/rocks/roca_04.png',
  './assets/rocks/roca_05.png',
  './assets/rocks/roca_06.png',
  './assets/rocks/roca_07.png',
  './assets/rocks/roca_08.png',
  './assets/rocks/roca_09.png',
  './assets/rocks/roca_10.png',
  './assets/rocks/roca_11.png',
  './assets/rocks/roca_12.png',
  './assets/rocks/roca_13.png',
  './assets/rocks/roca_14.png',
  './assets/rocks/roca_15.png',
  './assets/mobile/craters/001_crateres_separados_crater_01.png',
  './assets/mobile/craters/002_crateres_separados_crater_02.png',
  './assets/mobile/craters/003_crateres_separados_crater_03.png',
  './assets/mobile/craters/004_crateres_separados_crater_04.png',
  './assets/mobile/craters/005_crateres_separados_crater_05.png',
  './assets/mobile/craters/006_crateres_separados_crater_06.png',
  './assets/mobile/craters/007_crateres_separados_crater_07.png',
  './assets/mobile/craters/008_crateres_separados_crater_08.png',
  './assets/mobile/craters/009_crateres_separados_crater_09.png',
  './assets/mobile/craters/010_crateres_separados_crater_10.png',
  './assets/mobile/craters/011_crateres_separados_crater_11.png',
  './assets/mobile/craters/012_crateres_separados_crater_12.png',
  './assets/craters_flat/crater_plano_01.png',
  './assets/craters_flat/crater_plano_02.png',
  './assets/craters_flat/crater_plano_03.png',
  './assets/craters_flat/crater_plano_04.png',
  './assets/craters_flat/crater_plano_05.png',
  './assets/craters_flat/crater_plano_06.png',
  './assets/craters_flat/crater_plano_07.png',
  './assets/craters_flat/crater_plano_08.png',
  './assets/craters_flat/crater_plano_09.png',
  './assets/craters_flat/crater_plano_10.png',
  './assets/craters_flat/crater_plano_11.png',
  './assets/craters_flat/crater_plano_12.png',
  './assets/mobile/player/042_astronauta_3d_frames_todos_idle_01.png',
  './assets/mobile/player/043_astronauta_3d_frames_todos_idle_02.png',
  './assets/mobile/player/044_astronauta_3d_frames_todos_idle_03.png',
  './assets/mobile/player/045_astronauta_3d_frames_todos_idle_04.png',
  './assets/mobile/player/051_astronauta_3d_frames_todos_run_01.png',
  './assets/mobile/player/052_astronauta_3d_frames_todos_run_02.png',
  './assets/mobile/player/053_astronauta_3d_frames_todos_run_03.png',
  './assets/mobile/player/054_astronauta_3d_frames_todos_run_04.png',
  './assets/mobile/player/055_astronauta_3d_frames_todos_run_05.png',
  './assets/mobile/player/056_astronauta_3d_frames_todos_run_06.png',
  './assets/mobile/player/057_astronauta_3d_frames_todos_run_07.png',
  './assets/mobile/player/058_astronauta_3d_frames_todos_run_08.png',
  './assets/mobile/player/046_astronauta_3d_frames_todos_jump_01.png',
  './assets/mobile/player/047_astronauta_3d_frames_todos_jump_02.png',
  './assets/mobile/player/048_astronauta_3d_frames_todos_jump_03.png',
  './assets/mobile/player/049_astronauta_3d_frames_todos_jump_04.png',
  './assets/mobile/player/050_astronauta_3d_frames_todos_jump_05.png',
  './assets/mobile/player/035_astronauta_3d_frames_todos_fall_01.png',
  './assets/mobile/player/036_astronauta_3d_frames_todos_fall_02.png',
  './assets/mobile/player/037_astronauta_3d_frames_todos_fall_03.png',
  './assets/mobile/player/038_astronauta_3d_frames_todos_fall_04.png',
  './assets/mobile/player/029_astronauta_3d_frames_todos_attack_01.png',
  './assets/mobile/player/030_astronauta_3d_frames_todos_attack_02.png',
  './assets/mobile/player/031_astronauta_3d_frames_todos_attack_03.png',
  './assets/mobile/player/032_astronauta_3d_frames_todos_attack_04.png',
  './assets/mobile/player/033_astronauta_3d_frames_todos_attack_05.png',
  './assets/mobile/player/034_astronauta_3d_frames_todos_attack_06.png',
  './assets/mobile/player/039_astronauta_3d_frames_todos_hurt_01.png',
  './assets/mobile/player/040_astronauta_3d_frames_todos_hurt_02.png',
  './assets/mobile/player/041_astronauta_3d_frames_todos_hurt_03.png',
  './assets/mobile/worlds/001_paisaje_alienigena_luminoso_y_cristalino.jpg',
  './assets/mobile/worlds/004_ruinas_industriales_en_un_paisaje_alienigena.jpg',
  './assets/mobile/worlds/003_cueva_cristalina_iluminada_en_tonos_neon.jpg',
  './assets/mobile/worlds/011_ruinas_alienigenas_en_el_desierto_cosmico.jpg',
  './assets/mobile/worlds/008_pantano_alienigena_iluminado_por_neon.jpg',
  './assets/mobile/worlds/002_mundo_volcanico_alienigena_al_amanecer.jpg',
  './assets/mobile/worlds/010_paisaje_helado_alienigena_bajo_auroras.jpg',
  './assets/mobile/worlds/012_bosque_alienigena_bioluminiscente_en_el_crepusculo.jpg',
  './assets/mobile/parallax_foregrounds/001_terreno_alienigena_cristalino_y_luminoso.png',
  './assets/mobile/parallax_foregrounds/007_ruinas_industriales_alienigenas_iluminadas.png',
  './assets/mobile/parallax_foregrounds/008_cueva_de_cristal_luminosa_y_vibrante.png',
  './assets/mobile/parallax_foregrounds/005_ruinas_deserticas_al_atardecer.png',
  './assets/mobile/parallax_foregrounds/004_pantano_alienigena_toxico_iluminado.png',
  './assets/mobile/parallax_foregrounds/002_paisaje_volcanico_con_flujos_de_lava.png',
  './assets/mobile/parallax_foregrounds/003_paisaje_helado_y_cristalino_alienigena.png',
  './assets/mobile/parallax_foregrounds/006_bosque_alienigena_bioluminiscente_flotante.png',
  './assets/mobile/aliens/015_aliens_3d_movimientos_todos_idle.png',
  './assets/mobile/aliens/016_aliens_3d_movimientos_todos_walk.png',
  './assets/mobile/aliens/014_aliens_3d_movimientos_todos_hurt.png',
  './assets/mobile/aliens/013_aliens_3d_movimientos_todos_death.png',
  './assets/mobile/aliens/011_aliens_3d_movimientos_todos_idle.png',
  './assets/mobile/aliens/009_aliens_3d_movimientos_todos_float_move.png',
  './assets/mobile/aliens/010_aliens_3d_movimientos_todos_hurt.png',
  './assets/mobile/aliens/008_aliens_3d_movimientos_todos_death.png',
  './assets/mobile/aliens/005_aliens_3d_movimientos_todos_idle.png',
  './assets/mobile/aliens/003_aliens_3d_movimientos_todos_fly_move.png',
  './assets/mobile/aliens/004_aliens_3d_movimientos_todos_hurt.png',
  './assets/mobile/aliens/002_aliens_3d_movimientos_todos_death.png',
  './assets/mobile/bosses/006_boss_tentaculos_movimientos_idle.png',
  './assets/mobile/bosses/004_boss_tentaculos_movimientos_float_move.png',
  './assets/mobile/bosses/001_boss_tentaculos_movimientos_attack_1.png',
  './assets/mobile/bosses/005_boss_tentaculos_movimientos_hurt.png',
  './assets/mobile/bosses/011_bosses_movimientos_todos_idle.png',
  './assets/mobile/bosses/012_bosses_movimientos_todos_walk.png',
  './assets/mobile/bosses/007_bosses_movimientos_todos_attack_1.png',
  './assets/mobile/bosses/010_bosses_movimientos_todos_hurt.png',
  './assets/mobile/bosses/017_bosses_movimientos_todos_idle.png',
  './assets/mobile/bosses/018_bosses_movimientos_todos_walk.png',
  './assets/mobile/bosses/013_bosses_movimientos_todos_attack_1.png',
  './assets/mobile/bosses/016_bosses_movimientos_todos_hurt.png',
  './assets/mobile/platforms/021_suelos_perspectiva_pack_01_plataforma_futurista_cibernetica_iluminada.png',
  './assets/mobile/platforms/028_suelos_perspectiva_pack_08_plataforma_futurista_con_luces_neon.png',
  './assets/mobile/platforms/023_suelos_perspectiva_pack_03_plataforma_de_hierba_detallada_con_rocas.png',
  './assets/mobile/platforms/005_plataformas_3d_tamanos_05_plataforma_larga_hierba_roca.png',
  './assets/mobile/platforms/006_plataformas_3d_tamanos_06_plataforma_extra_larga_hierba.png',
  './assets/mobile/platforms/024_suelos_perspectiva_pack_04_plataforma_alienigena_con_slime_toxico.png',
  './assets/mobile/platforms/025_suelos_perspectiva_pack_05_plataforma_rocosa_en_un_desierto.png',
  './assets/mobile/platforms/010_plataformas_3d_tamanos_10_plataforma_larga_desertica.png',
  './assets/mobile/platforms/027_suelos_perspectiva_pack_07_plataforma_de_hielo_con_cristales.png',
  './assets/mobile/platforms/022_suelos_perspectiva_pack_02_plataforma_magica_futurista_en_perspectiva.png',
  './assets/mobile/platforms/007_plataformas_3d_tamanos_07_plataforma_grande_alien_teal.png',
  './assets/mobile/platforms/008_plataformas_3d_tamanos_08_plataforma_mediana_volcanica.png',
  './assets/mobile/platforms/026_suelos_perspectiva_pack_06_plataforma_volcanica_iluminada_en_lava.png',
  './assets/mobile/platforms/003_plataformas_3d_tamanos_03_plataforma_mediana_hierba.png',
  './assets/mobile/platforms/002_plataformas_3d_tamanos_02_plataforma_pequena_musgo.png',
  './assets/mobile/platforms/004_plataformas_3d_tamanos_04_plataforma_mediana_cristales_azules.png',
  './assets/mobile/platforms/001_plataformas_3d_tamanos_01_plataforma_pequena_redonda_arcana.png',
  './assets/mobile/platforms/017_plataformas_separadas_plataforma_media_02.png',
  './assets/platforms/ground_world_01_grass_crystal.png',
  './assets/platforms/ground_world_02_blue_biolume.png',
  './assets/platforms/ground_world_03_scifi.png',
  './assets/platforms/ground_world_04_desert_ruins.png',
  './assets/platforms/ground_world_05_toxic.png',
  './assets/platforms/ground_world_06_lava.png',
  './assets/platforms/ground_world_07_ice.png',
  './assets/mobile/traps/001_pack_trampas_cosmo_kid_01_trampa_pinchos_futurista.png',
  './assets/mobile/traps/002_pack_trampas_cosmo_kid_02_torreta_laser_horizontal.png',
  './assets/mobile/traps/003_pack_trampas_cosmo_kid_03_plataforma_trampa_holografica.png',
  './assets/mobile/traps/004_pack_trampas_cosmo_kid_04_generador_electrico.png',
  './assets/mobile/traps/005_pack_trampas_cosmo_kid_05_mina_flotante_morada.png',
  './assets/mobile/traps/006_pack_trampas_cosmo_kid_06_charco_slime_toxico.png',
  './assets/mobile/traps/007_pack_trampas_cosmo_kid_07_ventilacion_lava_erupcion.png',
  './assets/mobile/traps/008_pack_trampas_cosmo_kid_08_roca_colgante_trampa.png',
  './assets/mobile/traps_animated/001_pack_trampas_animadas_frames_01_trampa_pinchos_frame_01.png',
  './assets/mobile/traps_animated/002_pack_trampas_animadas_frames_01_trampa_pinchos_frame_02.png',
  './assets/mobile/traps_animated/003_pack_trampas_animadas_frames_01_trampa_pinchos_frame_03.png',
  './assets/mobile/traps_animated/004_pack_trampas_animadas_frames_01_trampa_pinchos_frame_04.png',
  './assets/mobile/traps_animated/005_pack_trampas_animadas_frames_01_trampa_pinchos_frame_05.png',
  './assets/mobile/traps_animated/006_pack_trampas_animadas_frames_01_trampa_pinchos_frame_06.png',
  './assets/mobile/traps_animated/007_pack_trampas_animadas_frames_02_torreta_laser_horizontal_frame_01.png',
  './assets/mobile/traps_animated/008_pack_trampas_animadas_frames_02_torreta_laser_horizontal_frame_02.png',
  './assets/mobile/traps_animated/009_pack_trampas_animadas_frames_02_torreta_laser_horizontal_frame_03.png',
  './assets/mobile/traps_animated/010_pack_trampas_animadas_frames_02_torreta_laser_horizontal_frame_04.png',
  './assets/mobile/traps_animated/011_pack_trampas_animadas_frames_02_torreta_laser_horizontal_frame_05.png',
  './assets/mobile/traps_animated/012_pack_trampas_animadas_frames_02_torreta_laser_horizontal_frame_06.png',
  './assets/mobile/traps_animated/013_pack_trampas_animadas_frames_03_plataforma_trampa_holografica_frame_01.png',
  './assets/mobile/traps_animated/014_pack_trampas_animadas_frames_03_plataforma_trampa_holografica_frame_02.png',
  './assets/mobile/traps_animated/015_pack_trampas_animadas_frames_03_plataforma_trampa_holografica_frame_03.png',
  './assets/mobile/traps_animated/016_pack_trampas_animadas_frames_03_plataforma_trampa_holografica_frame_04.png',
  './assets/mobile/traps_animated/017_pack_trampas_animadas_frames_03_plataforma_trampa_holografica_frame_05.png',
  './assets/mobile/traps_animated/018_pack_trampas_animadas_frames_03_plataforma_trampa_holografica_frame_06.png',
  './assets/mobile/traps_animated/019_pack_trampas_animadas_frames_04_generador_electrico_frame_01.png',
  './assets/mobile/traps_animated/020_pack_trampas_animadas_frames_04_generador_electrico_frame_02.png',
  './assets/mobile/traps_animated/021_pack_trampas_animadas_frames_04_generador_electrico_frame_03.png',
  './assets/mobile/traps_animated/022_pack_trampas_animadas_frames_04_generador_electrico_frame_04.png',
  './assets/mobile/traps_animated/023_pack_trampas_animadas_frames_04_generador_electrico_frame_05.png',
  './assets/mobile/traps_animated/024_pack_trampas_animadas_frames_04_generador_electrico_frame_06.png',
  './assets/mobile/traps_animated/025_pack_trampas_animadas_frames_05_mina_flotante_morada_frame_01.png',
  './assets/mobile/traps_animated/026_pack_trampas_animadas_frames_05_mina_flotante_morada_frame_02.png',
  './assets/mobile/traps_animated/027_pack_trampas_animadas_frames_05_mina_flotante_morada_frame_03.png',
  './assets/mobile/traps_animated/028_pack_trampas_animadas_frames_05_mina_flotante_morada_frame_04.png',
  './assets/mobile/traps_animated/029_pack_trampas_animadas_frames_05_mina_flotante_morada_frame_05.png',
  './assets/mobile/traps_animated/030_pack_trampas_animadas_frames_05_mina_flotante_morada_frame_06.png',
  './assets/mobile/traps_animated/031_pack_trampas_animadas_frames_06_charco_slime_toxico_frame_01.png',
  './assets/mobile/traps_animated/032_pack_trampas_animadas_frames_06_charco_slime_toxico_frame_02.png',
  './assets/mobile/traps_animated/033_pack_trampas_animadas_frames_06_charco_slime_toxico_frame_03.png',
  './assets/mobile/traps_animated/034_pack_trampas_animadas_frames_06_charco_slime_toxico_frame_04.png',
  './assets/mobile/traps_animated/035_pack_trampas_animadas_frames_06_charco_slime_toxico_frame_05.png',
  './assets/mobile/traps_animated/036_pack_trampas_animadas_frames_06_charco_slime_toxico_frame_06.png',
  './assets/mobile/traps_animated/037_pack_trampas_animadas_frames_07_ventilacion_lava_erupcion_frame_01.png',
  './assets/mobile/traps_animated/038_pack_trampas_animadas_frames_07_ventilacion_lava_erupcion_frame_02.png',
  './assets/mobile/traps_animated/039_pack_trampas_animadas_frames_07_ventilacion_lava_erupcion_frame_03.png',
  './assets/mobile/traps_animated/040_pack_trampas_animadas_frames_07_ventilacion_lava_erupcion_frame_04.png',
  './assets/mobile/traps_animated/041_pack_trampas_animadas_frames_07_ventilacion_lava_erupcion_frame_05.png',
  './assets/mobile/traps_animated/042_pack_trampas_animadas_frames_07_ventilacion_lava_erupcion_frame_06.png',
  './assets/mobile/traps_animated/043_pack_trampas_animadas_frames_08_roca_colgante_trampa_frame_01.png',
  './assets/mobile/traps_animated/044_pack_trampas_animadas_frames_08_roca_colgante_trampa_frame_02.png',
  './assets/mobile/traps_animated/045_pack_trampas_animadas_frames_08_roca_colgante_trampa_frame_03.png',
  './assets/mobile/traps_animated/046_pack_trampas_animadas_frames_08_roca_colgante_trampa_frame_04.png',
  './assets/mobile/traps_animated/047_pack_trampas_animadas_frames_08_roca_colgante_trampa_frame_05.png',
  './assets/mobile/traps_animated/048_pack_trampas_animadas_frames_08_roca_colgante_trampa_frame_06.png',
];

self.addEventListener('install', event => {
  self.skipWaiting();
  event.waitUntil(caches.open(COSMO_CACHE).then(cache => cache.addAll(CORE).catch(()=>{})));
});

self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys().then(keys => Promise.all(keys.filter(k => k !== COSMO_CACHE).map(k => caches.delete(k)))).then(()=>self.clients.claim())
  );
});

self.addEventListener('fetch', event => {
  const req = event.request;
  const url = new URL(req.url);
  if(req.method !== 'GET') return;

  // HTML: network first para evitar versiones viejas.
  if(req.headers.get('accept')?.includes('text/html') || url.pathname.endsWith('.html') || url.pathname.endsWith('/')) {
    event.respondWith(
      fetch(req, {cache:'no-store'}).then(res => {
        const copy = res.clone();
        caches.open(COSMO_CACHE).then(cache => cache.put(req, copy));
        return res;
    }).catch(() => caches.match(req).then(cached => cached || caches.match('./game.html?v=74')))
    );
    return;
  }

  // Assets: cache first.
  event.respondWith(
    caches.match(req).then(cached => cached || fetch(req).then(res => {
      const copy = res.clone();
      caches.open(COSMO_CACHE).then(cache => cache.put(req, copy));
      return res;
    }).catch(()=>cached))
  );
});
